# Generated by Django 4.2.1 on 2023-07-13 02:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('user', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('nickName', models.CharField(max_length=14)),
                ('userEmail', models.EmailField(max_length=254)),
                ('userPhone', models.CharField(max_length=12)),
                ('userImg', models.ImageField(default='jelly-carpet-ghz-g3d88c8d23_1280.jpg', upload_to='core')),
                ('bornDate', models.DateField(verbose_name='Fecha de nacimiento')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('idCategory', models.AutoField(primary_key=True, serialize=False)),
                ('categoryName', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('idRegion', models.AutoField(primary_key=True, serialize=False)),
                ('regionName', models.CharField(max_length=25)),
                ('shippingValue', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('idSale', models.AutoField(primary_key=True, serialize=False)),
                ('saleDate', models.DateField()),
                ('saleTotal', models.IntegerField()),
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.accounts')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('idProduct', models.AutoField(primary_key=True, serialize=False)),
                ('productName', models.CharField(max_length=150)),
                ('productDesc', models.CharField(max_length=300)),
                ('productValue', models.IntegerField(verbose_name='Valor del producto')),
                ('productStock', models.IntegerField(verbose_name='Stock disponible del producto')),
                ('productDiscount', models.IntegerField(verbose_name='Descuento del producto')),
                ('productImg', models.ImageField(upload_to='core')),
                ('idCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.category')),
            ],
        ),
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('idDetail', models.AutoField(primary_key=True, serialize=False)),
                ('productCount', models.IntegerField(verbose_name='Cantidad de Producto por pagar')),
                ('idProduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product')),
                ('idSale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.sale')),
            ],
        ),
        migrations.CreateModel(
            name='County',
            fields=[
                ('idCounty', models.AutoField(primary_key=True, serialize=False)),
                ('countyName', models.CharField(max_length=25)),
                ('idRegion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.region')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('idComent', models.AutoField(primary_key=True, serialize=False)),
                ('comentTxt', models.CharField(max_length=700, verbose_name='comentario de usuario')),
                ('comentPoints', models.IntegerField()),
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.accounts')),
                ('idProduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product')),
            ],
        ),
        migrations.CreateModel(
            name='Adress',
            fields=[
                ('idAdress', models.AutoField(primary_key=True, serialize=False)),
                ('streetAdress', models.CharField(max_length=50)),
                ('streetNumber', models.CharField(max_length=4)),
                ('descAdress', models.CharField(max_length=300)),
                ('postalCodeAdress', models.IntegerField()),
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.accounts')),
                ('idCounty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.county')),
            ],
        ),
    ]
